language: r

sudo: required

warnings_are_errors: true

notifications:
  email:
    recipients:
      - dbt1@williams.edu
    on_success: always
    on_failure: always

branches:
  only:
    - devel
    - travisTests
##  - master

install:
##  - Rscript -e "install.packages('devtools', repos = 'http://cran.us.r-project.org')"
  - Rscript -e "install.packages('igraph',   repos = 'http://cran.us.r-project.org')"
  - Rscript -e "install.packages('coda',     repos = 'http://cran.us.r-project.org')"
  - Rscript -e "install.packages('testthat', repos = 'http://cran.us.r-project.org')"
  - Rscript -e "install.packages('mvtnorm', repos = 'http://cran.us.r-project.org')"  ## needed for test-distributions.R
  - Rscript -e "install.packages('abind', repos = 'http://cran.us.r-project.org')"    ## needed for test-compareMCMCs.R
  - R CMD build packages/nimble
  - R CMD INSTALL packages/nimble

script:
##    - Rscript packages/nimble/inst/tests/test-mcmc.R    ##
##    - Rscript packages/nimble/inst/tests/test-models.R  ## about 50 mins for models+mcmc
##    - Rscript packages/nimble/inst/tests/test-getDependencies.R  ## basically no time added
##    - Rscript packages/nimble/inst/tests/test-getBound.R  ## basically no time added
##    - Rscript packages/nimble/inst/tests/test-declare.R  ## added ~5 mins
##    - Rscript packages/nimble/inst/tests/test-checkDSL.R  ## basically no time added
##    - Rscript packages/nimble/inst/tests/test-getParam.R  ## added ~4 mins
##    - Rscript packages/nimble/inst/tests/test-dsl_dists.R  ## basically no time added
##    - Rscript packages/nimble/inst/tests/test-user.R  ## added ~3 mins
##    - Rscript packages/nimble/inst/tests/test-setData.R  ## basically no time added
##    - Rscript packages/nimble/inst/tests/test-copy.R  ## added ~ 7 mins
##    - Rscript packages/nimble/inst/tests/test-trunc.R  ## added ~ 5 minutes
##    - Rscript packages/nimble/inst/tests/test-distributions.R  ## basically no time added
    - Rscript packages/nimble/inst/tests/test-misc.R  ## basically no time added
    - Rscript packages/nimble/inst/tests/test-size.R  ## basically no time added
    - Rscript packages/nimble/inst/tests/test-compareMCMCs.R  ## added ~2 minutes
    - Rscript packages/nimble/inst/tests/test-filtering.R  ## ???
##  - Rscript packages/nimble/inst/tests/test-getDistributionInfo.R  ## having issues with this one


##test-mcmc.R
##test-Mcmc2.R
##test-Mcmc3.R
##test-models.R
##test-getDependencies.R
##test-getBound.R
##test-declare.R
##test-checkDSL.R
##test-getParam.R
##test-dsl_dists.R
##test-user.R
##test-setData.R
##test-copy.R
##test-trunc.R
##test-distributions.R
##test-misc.R
##test-size.R
##test-compareMCMCs.R
##test-filtering.R
##test-Filtering2.R

##test-math.R
##test-Math2.R
##test-mcem.R
##test-getDistributionInfo.R



