language: r

sudo: required

warnings_are_errors: true

notifications:
  email:
    - dturek@berkeley.edu

branches:
  only:
    - master
    - devel

install:
  - Rscript -e "install.packages('devtools', repos = 'http://cran.us.r-project.org')"
  - Rscript -e "install.packages('igraph',   repos = 'http://cran.us.r-project.org')"
  - Rscript -e "install.packages('testthat', repos = 'http://cran.us.r-project.org')"
  - R CMD build packages/nimble
  - R CMD INSTALL packages/nimble

script:
##  - Rscript packages/nimble/tests/test-all.R    2>&1 | tee out
##                                                                ## initial travis setup: 14 mins
##  - Rscript packages/nimble/tests/test-mcmc.R   2>&1 | tee out
  - Rscript packages/nimble/tests/test-models.R 2>&1 | tee out
##  - Rscript packages/nimble/tests/test-trunc.R  2>&1 | tee out  ## PASS on devel, 7/29/15, 38 mins
##  - Rscript packages/nimble/tests/test-others.R 2>&1 | tee out  ## PASS on devel, 7/29/15, 31 mins

after_script:
  - sed -n -E '/[Ww]arning|[Ee]rror[^=]|[Ff]ailure/p' out > error
  - cat error
