language: r

sudo: required

warnings_are_errors: true

notifications:
  email:
    recipients:
      - dbt1@williams.edu
    on_success: always
    on_failure: always

branches:
  only:
    - devel
    - travisTests
##  - master

install:
##  - Rscript -e "install.packages('devtools', repos = 'http://cran.us.r-project.org')"
  - Rscript -e "install.packages('igraph',   repos = 'http://cran.us.r-project.org')"
  - Rscript -e "install.packages('coda',     repos = 'http://cran.us.r-project.org')"
  - Rscript -e "install.packages('testthat', repos = 'http://cran.us.r-project.org')"
  - Rscript -e "install.packages('mvtnorm', repos = 'http://cran.us.r-project.org')"  ## needed for test-distributions.R
  - Rscript -e "install.packages('abind', repos = 'http://cran.us.r-project.org')"    ## needed for test-compareMCMCs.R
  - R CMD build packages/nimble
  - R CMD INSTALL packages/nimble

script:
    - Rscript packages/nimble/inst/tests/test-checkDSL.R  ## basically no time added
    - Rscript packages/nimble/inst/tests/test-compareMCMCs.R  ## added ~2 minutes
    - Rscript packages/nimble/inst/tests/test-copy.R  ## added ~ 7 mins
    - Rscript packages/nimble/inst/tests/test-declare.R  ## added ~5 mins
    - Rscript packages/nimble/inst/tests/test-distributions.R  ## basically no time added
    - Rscript packages/nimble/inst/tests/test-dsl_dists.R  ## basically no time added
    - Rscript packages/nimble/inst/tests/test-filtering.R  ## added ~10 minutes
    - Rscript packages/nimble/inst/tests/test-getBound.R  ## basically no time added
    - Rscript packages/nimble/inst/tests/test-getDependencies.R  ## basically no time added
    - Rscript packages/nimble/inst/tests/test-getDistributionInfo.R  ## ???  causes errors??
    - Rscript packages/nimble/inst/tests/test-getParam.R  ## added ~4 mins
    - Rscript packages/nimble/inst/tests/test-math.R  ## added ~10 minutes
    - Rscript packages/nimble/inst/tests/test-mcem.R  ## added ~20 minutes
    - Rscript packages/nimble/inst/tests/test-mcmc.R    ##
    - Rscript packages/nimble/inst/tests/test-misc.R  ## basically no time added
    - Rscript packages/nimble/inst/tests/test-models.R  ## about 50 mins for models+mcmc
    - Rscript packages/nimble/inst/tests/test-setData.R  ## basically no time added
    - Rscript packages/nimble/inst/tests/test-size.R  ## basically no time added
    - Rscript packages/nimble/inst/tests/test-trunc.R  ## added ~ 5 minutes
    - Rscript packages/nimble/inst/tests/test-user.R  ## added ~3 mins

